1. .catch(err)
2. throw Error("This is an error")